# Generated by Django 2.1.3 on 2018-12-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingmaster',
            name='Eno',
            field=models.CharField(max_length=64),
        ),
    ]
